baseURL = 'https://www.gilly.garden/'
languageCode = 'en-us'
title = "Gilly's Garden"
theme="typo"

[params]
description="My personal blog where I grow ideas"
colorPalette = 'catpuccin'
homeCollectionTitle='Posts'

homeCollection='posts'
homeIntroContent="""
Welcome to my personal blog where I grow ideas related to computer science, art, and anything else that sparks my curiosity.
"""

paginationSize = 100
listSummaries = true
listDateFormat = '2 Jan 2006'

# Breadcrumbs
breadcrumbs = true

[[params.menu]]
name="home"
urls="/"

[[params.menu]]
name="tags"
urls="/tags"